spring.datasource.url=jdbc:postgresql://localhost/overall
spring.jpa.properties.hibernate.default_schema=overall
spring.datasource.username=postgres
spring.datasource.password=0023

spring.jpa.open-in-view=false
